#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -std=c++20 -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = -lopenal -lglfw -lGLEW -lX11 -lGLU -lGL -ldl -lpthread

INC_DEBUG = $(INC) -Iinclude -Iinclude/stages/ -Iinclude/entities -Iinclude/entities/
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS) lib/libPetroleum.a.debug
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/Gesneria

INC_RELEASE = $(INC) -Iinclude -Iinclude/stages/ -Iinclude/entities -Iinclude/entities/
CFLAGS_RELEASE = $(CFLAGS) -flto -O3
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -flto -s lib/libPetroleum.a
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/Gesneria

OBJ_DEBUG = $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/src/stages/Stage1.o $(OBJDIR_DEBUG)/src/entities/Player.o $(OBJDIR_DEBUG)/src/entities/Entity.o $(OBJDIR_DEBUG)/src/entities/Enemy.o $(OBJDIR_DEBUG)/src/entities/Bullet.o $(OBJDIR_DEBUG)/src/Stage.o $(OBJDIR_DEBUG)/src/Menu.o $(OBJDIR_DEBUG)/src/Application.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/src/stages/Stage1.o $(OBJDIR_RELEASE)/src/entities/Player.o $(OBJDIR_RELEASE)/src/entities/Entity.o $(OBJDIR_RELEASE)/src/entities/Enemy.o $(OBJDIR_RELEASE)/src/entities/Bullet.o $(OBJDIR_RELEASE)/src/Stage.o $(OBJDIR_RELEASE)/src/Menu.o $(OBJDIR_RELEASE)/src/Application.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/src/stages || mkdir -p $(OBJDIR_DEBUG)/src/stages
	test -d $(OBJDIR_DEBUG)/src/entities || mkdir -p $(OBJDIR_DEBUG)/src/entities
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/src/stages/Stage1.o: src/stages/Stage1.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/stages/Stage1.cpp -o $(OBJDIR_DEBUG)/src/stages/Stage1.o

$(OBJDIR_DEBUG)/src/entities/Player.o: src/entities/Player.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/entities/Player.cpp -o $(OBJDIR_DEBUG)/src/entities/Player.o

$(OBJDIR_DEBUG)/src/entities/Entity.o: src/entities/Entity.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/entities/Entity.cpp -o $(OBJDIR_DEBUG)/src/entities/Entity.o

$(OBJDIR_DEBUG)/src/entities/Enemy.o: src/entities/Enemy.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/entities/Enemy.cpp -o $(OBJDIR_DEBUG)/src/entities/Enemy.o

$(OBJDIR_DEBUG)/src/entities/Bullet.o: src/entities/Bullet.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/entities/Bullet.cpp -o $(OBJDIR_DEBUG)/src/entities/Bullet.o

$(OBJDIR_DEBUG)/src/Stage.o: src/Stage.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Stage.cpp -o $(OBJDIR_DEBUG)/src/Stage.o

$(OBJDIR_DEBUG)/src/Menu.o: src/Menu.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Menu.cpp -o $(OBJDIR_DEBUG)/src/Menu.o

$(OBJDIR_DEBUG)/src/Application.o: src/Application.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Application.cpp -o $(OBJDIR_DEBUG)/src/Application.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/src/stages
	rm -rf $(OBJDIR_DEBUG)/src/entities
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/src/stages || mkdir -p $(OBJDIR_RELEASE)/src/stages
	test -d $(OBJDIR_RELEASE)/src/entities || mkdir -p $(OBJDIR_RELEASE)/src/entities
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/src/stages/Stage1.o: src/stages/Stage1.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/stages/Stage1.cpp -o $(OBJDIR_RELEASE)/src/stages/Stage1.o

$(OBJDIR_RELEASE)/src/entities/Player.o: src/entities/Player.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/entities/Player.cpp -o $(OBJDIR_RELEASE)/src/entities/Player.o

$(OBJDIR_RELEASE)/src/entities/Entity.o: src/entities/Entity.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/entities/Entity.cpp -o $(OBJDIR_RELEASE)/src/entities/Entity.o

$(OBJDIR_RELEASE)/src/entities/Enemy.o: src/entities/Enemy.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/entities/Enemy.cpp -o $(OBJDIR_RELEASE)/src/entities/Enemy.o

$(OBJDIR_RELEASE)/src/entities/Bullet.o: src/entities/Bullet.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/entities/Bullet.cpp -o $(OBJDIR_RELEASE)/src/entities/Bullet.o

$(OBJDIR_RELEASE)/src/Stage.o: src/Stage.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Stage.cpp -o $(OBJDIR_RELEASE)/src/Stage.o

$(OBJDIR_RELEASE)/src/Menu.o: src/Menu.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Menu.cpp -o $(OBJDIR_RELEASE)/src/Menu.o

$(OBJDIR_RELEASE)/src/Application.o: src/Application.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Application.cpp -o $(OBJDIR_RELEASE)/src/Application.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/src/stages
	rm -rf $(OBJDIR_RELEASE)/src/entities
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

